version: '3'

tasks:
  all:
    cmds:
      - task: cleanup
      - task: build
      - task: package
      - task: adb
    silent: true

  build:
    cmds:
      - rm -rf build
      - mkdir -p build
      - mkdir -p build/lib
      - docker buildx build --platform=linux/arm64 -t retro-console-arm64 -f Dockerfile .
    silent: true

  package:
    cmds:
      - docker create --name extract retro-console-arm64
      - docker cp extract:/build/pak-store build/pak-store
      - docker cp extract:/usr/lib/aarch64-linux-gnu/libSDL2_gfx-1.0.so.0.0.2 build/lib/libSDL2_gfx-1.0.so.0
      - rm -rf build/Mortar.pak || true
      - mkdir -p build/Pak Store.pak
      - mkdir -p build/Pak Store.pak/resources/lib
      - cp build/pak-store launch.sh README.md LICENSE pak.json build/Pak Store.pak
      - cp -R build/lib build/Pak Store.pak/resources
    silent: true

  cleanup:
    cmds:
      - docker rm extract || true
    silent: true

  adb:
    cmds:
      - adb shell rm -rf /mnt/SDCARD/Tools/tg5040/Pak Store.pak || true
      - adb push build/Pak Store.pak /mnt/SDCARD/Tools/tg5040
      - say Finished deploying Pak Store!
    silent: true

  kill:
    cmds:
      - sshpass -p 'tina' ssh root@192.168.1.210 "kill  \$(pidof dlv)" > /dev/null 2>&1 || true
      - sshpass -p 'tina' ssh root@192.168.1.210 "kill  \$(pidof pak-store)" > /dev/null 2>&1 || true
    silent: true

  debug:
    cmds:
      - sshpass -p 'tina' ssh root@192.168.1.210 "sh -c '/mnt/SDCARD/Developer/bin/dlv attach --headless --listen=:2345 --api-version=2 --accept-multiclient \$(pidof pak-store)'" > /dev/null &
      - printf "Press any key to quit debugging...\n"
      - read
      - task: kill
    silent: true
