// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type InstalledPak struct {
	Name         string
	DisplayName  string
	RepoUrl      sql.NullString
	Type         string
	Version      string
	CanUninstall int64
}
