name: Package Pak Store

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Build
        run: env GOOS=linux GOARCH=arm64 go build -o pak-store app/pak-store.go

      - name: Build Package Folder
        run: |
          mkdir "Pak Store.pak"
          cp -R pak-store launch.sh README.md LICENSE pak.json resources/splash.png "Pak Store.pak"

      - uses: actions/upload-artifact@v4
        with:
          name: "Pak Store.pak"
          path: "Pak Store.pak"
          if-no-files-found: error
          retention-days: 3
          overwrite: true
