name: Build Storefront.json

on:
  workflow_dispatch:
  push:
    paths:
      - storefront_base.json
      - pak.json
      - app/storefront_builder.go
  schedule:
    - cron: "0 * * * *"

jobs:

  stock-shelves:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Build Storefront.json
        run: go run app/storefront_builder.go
        env:
          GOWORK: off
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp storefront.json deploy/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
