name: Package Pak Store

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Build and Package
        run: task build package

      - uses: actions/upload-artifact@v4
        with:
          name: "Pak Store.pak"
          path: "Pak Store.pak"
          if-no-files-found: error
          retention-days: 3
          overwrite: true
